#define BLACK 0x0000
#define BLUE 0x00F7
#define BLUE_LIGHT 0x00FA
#define BLUE_DARK 0x00F0
#define YELLOW 0xFF00
#define RED 0xF000
#define GREEN 0x0F00
#define ORANGE 0xAA0F
#define WHITE 0xFFFF

#define BG_COLOR BLACK
#define BTN_COLOR_ACTIVE 0xF000
#define GRAPH_COLOR WHITE
#define GRAPH_LOG_COLOR ORANGE
#define GRAPH_BG_COLOR BG_COLOR
#define GRAPG_TIMELINE_COLOR RED